# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.work_component import WorkComponent  # noqa: E501
from swagger_client.rest import ApiException


class TestWorkComponent(unittest.TestCase):
    """WorkComponent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkComponent(self):
        """Test WorkComponent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.work_component.WorkComponent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
