# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.person_resource import PersonResource  # noqa: E501
from swagger_client.rest import ApiException


class TestPersonResource(unittest.TestCase):
    """PersonResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPersonResource(self):
        """Test PersonResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.person_resource.PersonResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
