# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest
from common_routines import *

import swagger_client
# from models.subject import Subject  # noqa: E501
from swagger_client.rest import ApiException

class TestSubject(unittest.TestCase):
    """Subject unit test stubs"""

    def setUp(self):
        pass
    def tearDown(self):
        pass
    def testSubject(self):
        """Test Subject"""
        # model = swagger_client.models.subject.Subject()  # noqa: E501
        entityRoot(self, 'subject')
    # def testAddModifyRemove(self):
        addModifyRemoveNode(self, 'subject')
    # def testAddModifyRemoveChild(self):
        addModifyRemoveChildNode(self, 'subject')
    # def testNavigate(self):
        navigate(self, 'subject')
    # def testSubjectRemoveallButRoot(self):
        removeAllButRoot(self, 'subject')

    def testWork(self):
        """Test Work"""
        # model = swagger_client.models.subject.Subject()  # noqa: E501
        entityRoot(self, 'work')
        # def testAddModifyRemove(self):
        addModifyRemoveNode(self, 'work')
        # def testAddModifyRemoveChild(self):
        addModifyRemoveChildNode(self, 'work')
        # def testNavigate(self):
        navigate(self, 'work')
        # def testSubjectRemoveallButRoot(self):
        removeAllButRoot(self, 'work')

    def testPerson(self):
        """Test Person"""
        # model = swagger_client.models.subject.Subject()  # noqa: E501
        entityRoot(self, 'person')
        # def testAddModifyRemove(self):
        addModifyRemoveNode(self, 'person')
        # def testAddModifyRemoveChild(self):
        addModifyRemoveChildNode(self, 'person')
        # def testNavigate(self):
        navigate(self, 'person')
        # def testSubjectRemoveallButRoot(self):
        removeAllButRoot(self, 'person')

if __name__ == '__main__':
    unittest.main()
