# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.work_controller_api import WorkControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWorkControllerApi(unittest.TestCase):
    """WorkControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.work_controller_api.WorkControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_addwork2(self):
        """Test case for addwork2

        """
        pass

    def test_addwork3(self):
        """Test case for addwork3

        """
        pass

    def test_get_person_root4(self):
        """Test case for get_person_root4

        get root person  # noqa: E501
        """
        pass

    def test_get_subject_root4(self):
        """Test case for get_subject_root4

        get root subject  # noqa: E501
        """
        pass

    def test_get_work_root4(self):
        """Test case for get_work_root4

        get root work  # noqa: E501
        """
        pass

    def test_getworkbyid(self):
        """Test case for getworkbyid

        """
        pass

    def test_getworkbymysqlid(self):
        """Test case for getworkbymysqlid

        """
        pass

    def test_healthcheck5(self):
        """Test case for healthcheck5

        """
        pass

    def test_removefromlist1(self):
        """Test case for removefromlist1

        """
        pass


if __name__ == '__main__':
    unittest.main()
