# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.subject import Subject  # noqa: E501
from swagger_client.rest import ApiException


class TestSubject(unittest.TestCase):
    """Subject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubject(self):
        """Test Subject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.subject.Subject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
