# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.person_controller_api import PersonControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPersonControllerApi(unittest.TestCase):
    """PersonControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.person_controller_api.PersonControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_person(self):
        """Test case for add_person

        """
        pass

    def test_addwork(self):
        """Test case for addwork

        """
        pass

    def test_findby_legacyid(self):
        """Test case for findby_legacyid

        """
        pass

    def test_get_person_by_id(self):
        """Test case for get_person_by_id

        get root work  # noqa: E501
        """
        pass

    def test_get_person_root2(self):
        """Test case for get_person_root2

        get root person  # noqa: E501
        """
        pass

    def test_get_subject_root2(self):
        """Test case for get_subject_root2

        get root subject  # noqa: E501
        """
        pass

    def test_get_work_root2(self):
        """Test case for get_work_root2

        get root work  # noqa: E501
        """
        pass

    def test_healthcheck3(self):
        """Test case for healthcheck3

        """
        pass

    def test_remove_person(self):
        """Test case for remove_person

        """
        pass


if __name__ == '__main__':
    unittest.main()
