/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BuildProperties;
import io.swagger.client.model.PersonResource;
import io.swagger.client.model.SubjectRequest;
import io.swagger.client.model.SubjectResource;
import io.swagger.client.model.WorkResource;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SubjectControllerApi
 */
@Ignore
public class SubjectControllerApiTest {

    private final SubjectControllerApi api = new SubjectControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addsubjectTest() throws ApiException {
        SubjectRequest body = null;
        String relation = null;
        String parentid = null;
        SubjectResource response = api.addsubject(body, relation, parentid);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addwork1Test() throws ApiException {
        SubjectRequest body = null;
        String id = null;
        SubjectResource response = api.addwork1(body, id);

        // TODO: test validations
    }
    /**
     * get root person
     *
     * get the root node for person
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPersonRoot3Test() throws ApiException {
        PersonResource response = api.getPersonRoot3();

        // TODO: test validations
    }
    /**
     * get root subject
     *
     * get the root node for person
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSubjectRoot3Test() throws ApiException {
        SubjectResource response = api.getSubjectRoot3();

        // TODO: test validations
    }
    /**
     * get root work
     *
     * get the root node for person
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWorkRoot3Test() throws ApiException {
        WorkResource response = api.getWorkRoot3();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getsubjectbyidTest() throws ApiException {
        String id = null;
        SubjectResource response = api.getsubjectbyid(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getsubjectbylegacyidTest() throws ApiException {
        String id = null;
        SubjectResource response = api.getsubjectbylegacyid(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void healthcheck4Test() throws ApiException {
        BuildProperties response = api.healthcheck4();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removefromlistTest() throws ApiException {
        String id = null;
        Boolean deletesubtree = null;
        String response = api.removefromlist(id, deletesubtree);

        // TODO: test validations
    }
}
