/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * LinkRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-12T15:49:33.774Z[GMT]")
public class LinkRequest {
  @SerializedName("sourceid")
  private String sourceid = null;

  @SerializedName("targetid")
  private String targetid = null;

  public LinkRequest sourceid(String sourceid) {
    this.sourceid = sourceid;
    return this;
  }

   /**
   * Get sourceid
   * @return sourceid
  **/
  @Schema(description = "")
  public String getSourceid() {
    return sourceid;
  }

  public void setSourceid(String sourceid) {
    this.sourceid = sourceid;
  }

  public LinkRequest targetid(String targetid) {
    this.targetid = targetid;
    return this;
  }

   /**
   * Get targetid
   * @return targetid
  **/
  @Schema(description = "")
  public String getTargetid() {
    return targetid;
  }

  public void setTargetid(String targetid) {
    this.targetid = targetid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkRequest linkRequest = (LinkRequest) o;
    return Objects.equals(this.sourceid, linkRequest.sourceid) &&
        Objects.equals(this.targetid, linkRequest.targetid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceid, targetid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkRequest {\n");
    
    sb.append("    sourceid: ").append(toIndentedString(sourceid)).append("\n");
    sb.append("    targetid: ").append(toIndentedString(targetid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
