# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class BuildProperties(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'time': 'datetime',
        'version': 'str',
        'group': 'str',
        'artifact': 'str',
        'name': 'str'
    }

    attribute_map = {
        'time': 'time',
        'version': 'version',
        'group': 'group',
        'artifact': 'artifact',
        'name': 'name'
    }

    def __init__(self, time=None, version=None, group=None, artifact=None, name=None):  # noqa: E501
        """BuildProperties - a model defined in Swagger"""  # noqa: E501
        self._time = None
        self._version = None
        self._group = None
        self._artifact = None
        self._name = None
        self.discriminator = None
        if time is not None:
            self.time = time
        if version is not None:
            self.version = version
        if group is not None:
            self.group = group
        if artifact is not None:
            self.artifact = artifact
        if name is not None:
            self.name = name

    @property
    def time(self):
        """Gets the time of this BuildProperties.  # noqa: E501


        :return: The time of this BuildProperties.  # noqa: E501
        :rtype: datetime
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this BuildProperties.


        :param time: The time of this BuildProperties.  # noqa: E501
        :type: datetime
        """

        self._time = time

    @property
    def version(self):
        """Gets the version of this BuildProperties.  # noqa: E501


        :return: The version of this BuildProperties.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this BuildProperties.


        :param version: The version of this BuildProperties.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def group(self):
        """Gets the group of this BuildProperties.  # noqa: E501


        :return: The group of this BuildProperties.  # noqa: E501
        :rtype: str
        """
        return self._group

    @group.setter
    def group(self, group):
        """Sets the group of this BuildProperties.


        :param group: The group of this BuildProperties.  # noqa: E501
        :type: str
        """

        self._group = group

    @property
    def artifact(self):
        """Gets the artifact of this BuildProperties.  # noqa: E501


        :return: The artifact of this BuildProperties.  # noqa: E501
        :rtype: str
        """
        return self._artifact

    @artifact.setter
    def artifact(self, artifact):
        """Sets the artifact of this BuildProperties.


        :param artifact: The artifact of this BuildProperties.  # noqa: E501
        :type: str
        """

        self._artifact = artifact

    @property
    def name(self):
        """Gets the name of this BuildProperties.  # noqa: E501


        :return: The name of this BuildProperties.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BuildProperties.


        :param name: The name of this BuildProperties.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BuildProperties, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BuildProperties):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
