# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Work(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'get_id': 'str',
        'legacyid': 'str',
        'title': 'str',
        'tags': 'list[str]',
        'components': 'list[WorkComponent]',
        'work_relations': 'list[Link]',
        'work_parents': 'list[Link]',
        'person_parents': 'list[Link]',
        'subject_parents': 'list[Link]'
    }

    attribute_map = {
        'get_id': 'get_id',
        'legacyid': 'legacyid',
        'title': 'title',
        'tags': 'tags',
        'components': 'components',
        'work_relations': 'work_relations',
        'work_parents': 'work_parents',
        'person_parents': 'person_parents',
        'subject_parents': 'subject_parents'
    }

    def __init__(self, get_id=None, legacyid=None, title=None, tags=None, components=None, work_relations=None, work_parents=None, person_parents=None, subject_parents=None):  # noqa: E501
        """Work - a model defined in Swagger"""  # noqa: E501
        self._get_id = None
        self._legacyid = None
        self._title = None
        self._tags = None
        self._components = None
        self._work_relations = None
        self._work_parents = None
        self._person_parents = None
        self._subject_parents = None
        self.discriminator = None
        if get_id is not None:
            self.get_id = get_id
        if legacyid is not None:
            self.legacyid = legacyid
        if title is not None:
            self.title = title
        if tags is not None:
            self.tags = tags
        if components is not None:
            self.components = components
        if work_relations is not None:
            self.work_relations = work_relations
        if work_parents is not None:
            self.work_parents = work_parents
        if person_parents is not None:
            self.person_parents = person_parents
        if subject_parents is not None:
            self.subject_parents = subject_parents

    @property
    def get_id(self):
        """Gets the get_id of this Work.  # noqa: E501


        :return: The get_id of this Work.  # noqa: E501
        :rtype: str
        """
        return self._get_id

    @get_id.setter
    def get_id(self, get_id):
        """Sets the get_id of this Work.


        :param get_id: The get_id of this Work.  # noqa: E501
        :type: str
        """

        self._get_id = get_id

    @property
    def legacyid(self):
        """Gets the legacyid of this Work.  # noqa: E501


        :return: The legacyid of this Work.  # noqa: E501
        :rtype: str
        """
        return self._legacyid

    @legacyid.setter
    def legacyid(self, legacyid):
        """Sets the legacyid of this Work.


        :param legacyid: The legacyid of this Work.  # noqa: E501
        :type: str
        """

        self._legacyid = legacyid

    @property
    def title(self):
        """Gets the title of this Work.  # noqa: E501


        :return: The title of this Work.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Work.


        :param title: The title of this Work.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def tags(self):
        """Gets the tags of this Work.  # noqa: E501


        :return: The tags of this Work.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this Work.


        :param tags: The tags of this Work.  # noqa: E501
        :type: list[str]
        """

        self._tags = tags

    @property
    def components(self):
        """Gets the components of this Work.  # noqa: E501


        :return: The components of this Work.  # noqa: E501
        :rtype: list[WorkComponent]
        """
        return self._components

    @components.setter
    def components(self, components):
        """Sets the components of this Work.


        :param components: The components of this Work.  # noqa: E501
        :type: list[WorkComponent]
        """

        self._components = components

    @property
    def work_relations(self):
        """Gets the work_relations of this Work.  # noqa: E501


        :return: The work_relations of this Work.  # noqa: E501
        :rtype: list[Link]
        """
        return self._work_relations

    @work_relations.setter
    def work_relations(self, work_relations):
        """Sets the work_relations of this Work.


        :param work_relations: The work_relations of this Work.  # noqa: E501
        :type: list[Link]
        """

        self._work_relations = work_relations

    @property
    def work_parents(self):
        """Gets the work_parents of this Work.  # noqa: E501


        :return: The work_parents of this Work.  # noqa: E501
        :rtype: list[Link]
        """
        return self._work_parents

    @work_parents.setter
    def work_parents(self, work_parents):
        """Sets the work_parents of this Work.


        :param work_parents: The work_parents of this Work.  # noqa: E501
        :type: list[Link]
        """

        self._work_parents = work_parents

    @property
    def person_parents(self):
        """Gets the person_parents of this Work.  # noqa: E501


        :return: The person_parents of this Work.  # noqa: E501
        :rtype: list[Link]
        """
        return self._person_parents

    @person_parents.setter
    def person_parents(self, person_parents):
        """Sets the person_parents of this Work.


        :param person_parents: The person_parents of this Work.  # noqa: E501
        :type: list[Link]
        """

        self._person_parents = person_parents

    @property
    def subject_parents(self):
        """Gets the subject_parents of this Work.  # noqa: E501


        :return: The subject_parents of this Work.  # noqa: E501
        :rtype: list[Link]
        """
        return self._subject_parents

    @subject_parents.setter
    def subject_parents(self, subject_parents):
        """Sets the subject_parents of this Work.


        :param subject_parents: The subject_parents of this Work.  # noqa: E501
        :type: list[Link]
        """

        self._subject_parents = subject_parents

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Work, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Work):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
